-- Hack for compatibility between MySQL and SQLite.
-- SQLite does not support AUTO_INCREMENT.

ALTER TABLE Pokemon MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE PokemonItems MODIFY COLUMN ownerid INT NOT NULL AUTO_INCREMENT;
ALTER TABLE PokemonUsers MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;